"""Constants for tests."""

from __future__ import annotations

from aiohomematic_test_support.const import CCU_PASSWORD, CCU_USERNAME, CENTRAL_NAME, INTERFACE_ID

__all__ = ["INTERFACE_ID"]
CONFIG_ENTRY_ID = "12345678"
CONFIG_ENTRY_UNIQUE_ID = "9876543210"
DEFAULT_CALLBACK_PORT = 8967
HOST = "127.0.0.1"
INSTANCE_NAME = CENTRAL_NAME
INVALID_PASSWORD = "In_VäLid"
SERIAL = "0987654321"
USERNAME = CCU_USERNAME
PASSWORD = CCU_PASSWORD
